### ISSUE TITLE
Help with Error!

### ISSUE THREAD

**Issue by Hann1bal** [Yupeek/django-rest-models#11]
```

Unhandled exception in thread started by <function wrapper at 0x031C2830>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.
py", line 117, in inner_run
    autoreload.raise_last_exception()
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 250, in
raise_last_exception
    six.reraise(*_exception)
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\__init__.py", line 27, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "C:\Python27\lib\site-packages\django\apps\registry.py", line 85, in popu
late
    app_config = AppConfig.create(entry)
  File "C:\Python27\lib\site-packages\django\apps\config.py", line 94, in create

    module = import_module(entry)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
ImportError: No module named openmrs-python
Performing system checks...

Unhandled exception in thread started by <function wrapper at 0x034B14B0>
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\django\utils\autoreload.py", line 227, in
wrapper
    fn(*args, **kwargs)
  File "C:\Python27\lib\site-packages\django\core\management\commands\runserver.
py", line 125, in inner_run
    self.check(display_num_errors=True)
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 359,
 in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Python27\lib\site-packages\django\core\management\base.py", line 346,
 in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Python27\lib\site-packages\django\core\checks\registry.py", line 81,
in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 16, in c
heck_url_config
    return check_resolver(resolver)
  File "C:\Python27\lib\site-packages\django\core\checks\urls.py", line 26, in c
heck_resolver
    return check_method()
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 254, in ch
eck
    for pattern in self.url_patterns:
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in _
_get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 405, in ur
l_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Python27\lib\site-packages\django\utils\functional.py", line 35, in _
_get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Python27\lib\site-packages\django\urls\resolvers.py", line 398, in ur
lconf_module
    return import_module(self.urlconf_name)
  File "C:\Python27\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Hann1bal\Desktop\rest\rest\rest\urls.py", line 19, in <module>
    from restapi import views
  File "C:\Users\Hann1bal\Desktop\rest\rest\restapi\views.py", line 8, in <modul
e>
    from .serializers import PatientSerializer
  File "C:\Users\Hann1bal\Desktop\rest\rest\restapi\serializers.py", line 1, in
<module>
    from dynamic_rest.serializers import DynamicModelSerializer
ImportError: No module named dynamic_rest.serializers

```

**Comment by Hann1bal** [comment]
from dynamic_rest.serializers import DynamicModelSerializer
from dynamic_rest.fields.fields import DynamicRelationField

from .models import Patient

class PatientIdentifierSerializer(DynamicModelSerializer): 

    patients = DynamicRelationsField ('PatientSerializer', many=True)
	
    class Meta:
        model = PatientIdentifier
        name = 'auditmodelbase'
        fields = '__all__'
        
class PatientIdentifierTypeSerializer(DynamicModelSerializer):
    auditmodelbase = DynamicRelationsField(AuditModelBaseSerializer)
	
    class Meta:
        model = PatientIdentifierType
        name = 'patient'
        filds = '__all__'
        
        
class PersonSerializer(DynamicModelSerializer):
    auditmodelbase = DynamicRelationsField(AuditModelBaseSerializer)
	
    class Meta:
        model = Person
        name = 'patient'
        filds = '__all__'

**Comment by ornoone** [comment]
please, don't post your code and trackback without event a minimal formating, and without a word of explanation. 

can you post : 

- your `pip freeze` output 
- your INSTALLED_APP settings
- your DATABASES settings (without password and others sensible stuff)

is this output in your api or in your client ? you post an issue into django-rest-models repo, but all I see is a stuff to create a rest api with dynamic-rest

**Comment by ornoone** [comment]
no news from the poster. feel free to reopen.
