### ISSUE TITLE
Cannot create an object with a JSONField

### ISSUE THREAD

**Issue by PaulWay** [Yupeek/django-rest-models#37]
I've got a REST API model using a JSONField:

```python
class Host(models.Model):
    account = models.CharField(max_length=10)
    display_name = models.CharField(max_length=200)
    created_on = models.DateTimeField(auto_now_add=True)
    modified_on = models.DateTimeField(auto_now=True)
    facts = JSONField(null=True)
    tags = JSONField(null=True)
    canonical_facts = JSONField(null=True)

    class APIMeta:
        db_name = 'inventoryapi'
        resource_path = 'hosts/'
```

I can't save an object, because the 'JsonAdapter' object can't be serialised into JSON:
```
>>> h = Host(display_name='system1.example.net', account='1122334', canonical_facts={'insights_uuid': '02468135-7902-4681-3579-024681357902'})
>>> h.save()
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/base.py", line 718, in save
    force_update=force_update, update_fields=update_fields)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/base.py", line 748, in save_base
    updated = self._save_table(raw, cls, force_insert, force_update, using, update_fields)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/base.py", line 831, in _save_table
    result = self._do_insert(cls._base_manager, using, fields, update_pk, raw)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/base.py", line 869, in _do_insert
    using=using, raw=raw)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/manager.py", line 82, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/django/db/models/query.py", line 1136, in _insert
    return query.get_compiler(using=using).execute_sql(return_id)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/compiler.py", line 1031, in execute_sql
    json=json
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/connexion.py", line 152, in post
    return self.request("post", url, params=params, json=json, **kwargs)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/connexion.py", line 218, in request
    return self.connection.request(method, url, **kwargs)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/connexion.py", line 383, in request
    response = execute("%s %s" % (method.upper(), real_url), dict(method=method, url=real_url, **kwargs))
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/connexion.py", line 312, in execute
    return self._make_request(params)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/rest_models/backend/connexion.py", line 329, in _make_request
    response = self.session.request(**params)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/requests/sessions.py", line 498, in request
    prep = self.prepare_request(req)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/requests/sessions.py", line 441, in prepare_request
    hooks=merge_hooks(request.hooks, self.hooks),
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/requests/models.py", line 312, in prepare
    self.prepare_body(data, files, json)
  File "/home/pwayper/.local/share/virtualenvs/insights-advisor-api-33rkQyHO/lib/python3.6/site-packages/requests/models.py", line 462, in prepare_body
    body = complexjson.dumps(json)
  File "/usr/lib64/python3.6/json/__init__.py", line 231, in dumps
    return _default_encoder.encode(obj)
  File "/usr/lib64/python3.6/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/lib64/python3.6/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/usr/lib64/python3.6/json/encoder.py", line 180, in default
    o.__class__.__name__)
TypeError: Object of type 'JsonAdapter' is not JSON serializable
```
I think what needs to happen here is that either the JSON is dumped into a string in the backend connexion code prior to being given to the `requests`, or it is left as a structure rather than being a JSON object so that the regular dict serialisers can work.  But I'm not experienced enough with the connexion code to know where to do that.

Any idea on how to get this to work?

**Comment by ornoone** [comment]
thanks for your message.
I checked this specific case and it seem JSONField is a field specific to postgresql. at first I just subclassed the JSONField and rewrote the `get_prep_value`, but it will be harder than that to fix. there are two problems:

- handling serialisation/deserialisation of JSONField to send it to the api (i don't know if JSONField is compatible with django-rest-framework at first)
- handling lookup specifics to JSONField which include some extra.

in short, if you check the code of JSONField, you will se many postgresql specificities which will prevent this field to be compatible with our lib without some work, and I don't have the time for now.

i you whant, i have added a feature branch named `jsonfield-compat` in which you can continue my work. I added:
- a unit test doing a post with this field
- a subclass for JSONField which fix the serialisation problem.

the next step is :
- write more tests (all specials lookup, delete, get, update)
- write what is needed to support all specifics lookup of this field.

**Comment by PaulWay** [comment]
Is monkey-patching a better approach than deriving a new class?

https://stackoverflow.com/questions/18478287/making-object-json-serializable-with-regular-encoder/18561055

**Comment by ornoone** [comment]
hey, thanks for your help. I will follow AltSchool/dynamic-rest#257.

I tend to never monkey-patch if I have the choice. it's the best way to make conflict with other libs,and in our case, it will just make some models less verbose... one import line is not worth the cost.

If it's really a problem to import a custom field, i still can play with the connector itself to support the serialization.

**Comment by PaulWay** [comment]
I'm not really keen on having to use a custom field as it changes the model from the text I'm copying across from the other project.  Then I have to explain why I'm using this custom field and not the JSONField like the original model :-)

It feels to me like serialising JSON into JSON should be trivial - it's really just a substructure.  So I don't know why this isn't already done somewhere else :-)

**Comment by PaulWay** [comment]
I've done a bit of work this morning and actually got lookups working with the code in this branch:

https://github.com/Yupeek/django-rest-models/pull/38

It's a bit of a hack but it may be useful as a starting point.

**Comment by ornoone** [comment]
hey paul, thanks for the PR. I worked on writing unit-tests and IC tests to check if this feature work or not.

for now, it's failing as expected since KeyTransform don't behave as Col do in our lib.

for the problem about the custom JSONField, I clearly understand your point of view, but I refuse to do anything intrusive in the lib of the user of our package. so we have 3 options:
- monkey-patch base json encode (feel bad)
- force models of APIModels to use our small custom field (which can have the same name as the original, which ease copy-past)
- monkey-patch instance of field of APIModels at init to overwrite `get_prep_value` at runtime.

IMHO, zen of python state `explicit is better than implicit` and a implicit monkey-patch feel worst than an explicit import

**Comment by PaulWay** [comment]
Hi @ornoone - I agree that monkey patching the JSONField is ugly.  I've gone with your custom `DrmJSONField` class, in the models module, with some explanatory comments :-)

I'll try pushing this upstream to the Postgres and MySQL Django connectors that implement JSONField to see how that's received.

I agree that my Transform handling is a hack.  Unfortunately I don't know how better to do it :-)  What's not working for you?  It seems to be working for me - in fact, it's amazing since awesome JSON queries go transparently through to the other side and get handled by Postgres seamlessly!

**Comment by ornoone** [comment]
it work for me for CRUD, but I have a exception as soon as I try to do a lookup on the inner json data (as expected)

see the test `rest_models.tests.tests_queryset.TestJsonField.test_jsonfield_lookup` fail with the error `AttributeError: 'KeyTransform' object has no attribute 'alias'` on compiler.py:417 

as for now, I don't know how to handle this issue, it require more work to understand how is expected the query from drest and how i will detect this is not a query about a related field, but a specific field

**Comment by PaulWay** [comment]
I thought there might be a better way by passing an encoder function or class in the `encoder` argument to the JSONField, but no - that still doesn't solve the problem that the JSONField is not inherently serialisable.

**Comment by PaulWay** [comment]
It turns out I also needed to patch the handling of `Transform` objects into the `extract_exact_pk_value` function in `backend/compiler.py`.  The diff is here:

https://github.com/Yupeek/django-rest-models/pull/39
